WayfError: do not encode errorText with ESAPI
WayfError is already preformatted correctly escaped HTML - does not need
ESAPI (and ESAPI otherwise breaks HTML formatting already included in
error messages).